### ISSUE TITLE
[Improvement] Handle common exceptions

### ISSUE THREAD

**Issue by BinToss** [Kuinox/NupkgDeterministicator#1]
- [x] #3
- [x] #6

**Comment by Kuinox** [comment]
Oh hello, I'm surprised someone is using this after this long !  
> Cannot deterministicate a nupkg/snupkg that is already deterministic  

Yes, i'll add a check for this.  

> Add help (-h/--help) argument
> An argument like this, which always exits with code 0, would be helpful in cross-platform MSBuild tasks to check if NupkgDeterministicator is installed before executing it after Pack.  

Ideally I should rewrite the entrypoint with System.CommandLine, which also handle transparently msbuild response file.  

I will do it tomorrow or this we, you can also PR it if you want.

**Comment by BinToss** [comment]
I didn't expect such a quick response! I think I can open a PR for the help arg tonight if I rush it.

**Comment by Kuinox** [comment]
Mind that when it will be rewritten with system.command line the help prompt will be triggered differently than the very simple in-test there is right now.

**Comment by BinToss** [comment]
All sub-issues resolved.
